### PR TITLE
fix issue 213 related to targetSdk 29 and Android 9.0 or greater;

### PR DESCRIPTION
**Pull request by AlexanderShniperson**
fix issue #213 related to targetSdk 29 and Android 9.0 or greater;
i made fixes as it required by documentation
`
Permission for USB devices of class UsbConstants#USB_CLASS_VIDEO for clients that target SDK Build.VERSION_CODES.P and above can be granted only if they have additionally the Manifest.permission.CAMERA permission. 
`
also refactored camera initialization.

### CODE REVIEW

**Comment by AlexanderShniperson** [comment]
typo in comment
 rollback to targetSdk 27 and compileSdk 28, now disconnect works fine, also approved work at Android 10

**Comment by AlexanderShniperson** [comment]
here is stack trace fatal error in C-library when compiled with targetSdk=29 and try to disconnect camera
```
2020-04-21 11:39:34.056 21033-21204/com.example.cam A/libc: FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7782c28c34)
2020-04-21 11:39:34.063 21033-21204/com.example.cam A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 21204 (CameraThread), pid 21033 (m.inostudio.dar)
2020-04-21 11:39:34.155 21265-21265/? E/crash_dump64: failed to interrupt 21216 to detach: No such process
2020-04-21 11:39:34.155 21265-21265/? E/crash_dump64: failed to interrupt 21218 to detach: No such process
2020-04-21 11:39:34.228 21271-21271/? E/com.android.mt: Not starting debugger since process cannot load the jdwp agent.
2020-04-21 11:39:34.234 1137-1797/? E/ProcessInfoCollector: getProcessInfo: failed to find this proc 
2020-04-21 11:39:34.264 21265-21265/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-04-21 11:39:34.264 21265-21265/? A/DEBUG: Build fingerprint: 'HUAWEI/VTR-L29/HWVTR:9/HUAWEIVTR-L29/252C10:user/release-keys'
2020-04-21 11:39:34.264 21265-21265/? A/DEBUG: Revision: '0'
2020-04-21 11:39:34.264 21265-21265/? A/DEBUG: ABI: 'arm64'
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG: Happend: 'Tue Apr 21 11:39:34 2020
    '
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG: SYSVMTYPE: Art
    APPVMTYPE: Art
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG: pid: 21033, tid: 21204, name: CameraThread  >>> com.example.cam <<<
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG: Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7782c28c34)'
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x0  0000000000000000  x1  00000000000052d4  x2  0000000000000006  x3  0000000000000008
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  0000000000000038
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x8  0000000000000083  x9  771b5fe2251eb481  x10 0000000000000000  x11 fffffffc7ffffbdf
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x12 0000000000000001  x13 000000005e9eb146  x14 0000c8e54629520d  x15 00000d0507354ccd
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x16 0000007838a722c0  x17 00000078389b0e34  x18 0000000000000001  x19 0000000000005229
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x20 00000000000052d4  x21 000000000000000c  x22 0000000000000004  x23 0000007782c28c00
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x24 0000007782c28e20  x25 00000077ae640220  x26 0000007796b4e7c0  x27 0000000000000003
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     x28 0000000000000004  x29 0000007782348130
2020-04-21 11:39:34.265 21265-21265/? A/DEBUG:     sp  00000077823480f0  lr  00000078389a5960  pc  00000078389a5988
2020-04-21 11:39:34.270 21265-21265/? A/DEBUG: backtrace:
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #00 pc 0000000000022988  /system/lib64/libc.so (abort+116)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #01 pc 0000000000084b54  /system/lib64/libc.so (__fortify_fatal(char const*, ...)+120)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #02 pc 0000000000084250  /system/lib64/libc.so (HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)+52)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #03 pc 0000000000084104  /system/lib64/libc.so (pthread_mutex_lock+228)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #04 pc 00000000000118a0  /data/app/com.example.cam-Yxl3p1K-dL0k0vInGn0ovg==/base.apk (offset 0x6e000)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #05 pc 000000000000d618  /data/app/com.example.cam-Yxl3p1K-dL0k0vInGn0ovg==/base.apk (offset 0x6e000)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #06 pc 000000000000d060  /data/app/com.example.cam-Yxl3p1K-dL0k0vInGn0ovg==/base.apk (offset 0x6e000) (libusb_handle_events_timeout_completed+600)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #07 pc 000000000000d774  /data/app/com.example.cam-Yxl3p1K-dL0k0vInGn0ovg==/base.apk (offset 0x6e000) (libusb_handle_events+32)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #08 pc 00000000000114fc  /data/app/com.example.cam-Yxl3p1K-dL0k0vInGn0ovg==/base.apk (offset 0x4000) (_uvc_handle_events+132)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #09 pc 0000000000083588  /system/lib64/libc.so (__pthread_start(void*)+36)
2020-04-21 11:39:34.271 21265-21265/? A/DEBUG:     #10 pc 00000000000241dc  /system/lib64/libc.so (__start_thread+68)
```

**Comment by 41108871** [comment]
Hi @AlexanderShniperson 
Coulde you give me a apk which you have test on your Android 10？ I want to test on my Android 10，whether  usb camera can preview on my phone。My email is 41108871@qq.com

**Comment by YuSiwenXC** [comment]
@AlexanderShniperson BTW, this error only occured in RUN, but not Build. Build is OK.

**Pull request merged**
